In [31]:
import pandas as pd
import numpy as np

In [50]:
data = pd.read_csv("tap_fun_train.csv", parse_dates=True)
data_test = pd.read_csv("tap_fun_test.csv", parse_dates=True)

In [4]:
data

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
0,1,2018-02-02 19:47:15,20125.0,3700.0,0.0,0.0,0.0,0.0,16375.0,2000.0,...,0,0,0,0,0,0,0.333333,0.00,0,0.00
1,1593,2018-01-26 00:01:05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.00,0,0.00
2,1594,2018-01-26 00:01:58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.166667,0.00,0,0.00
3,1595,2018-01-26 00:02:13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.166667,0.00,0,0.00
4,1596,2018-01-26 00:02:46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,2.333333,0.00,0,0.00
5,1597,2018-01-26 00:03:06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.166667,0.00,0,0.00
6,1598,2018-01-26 00:03:45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,4.000000,0.00,0,0.00
7,1599,2018-01-26 00:04:11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.666667,0.00,0,0.00
8,1600,2018-01-26 00:06:01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.833333,0.00,0,0.00
9,1601,2018-01-26 00:07:42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.500000,0.00,0,0.00
10,1602,2018-01-26 00:07:47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.833333,0.00,0,0.00
11,1603,2018-01-26 00:10:27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.000000,0.00,0,0.00
12,1604,2018-01-26 00:10:34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.000000,0.00,0,0.00
13,1605,2018-01-26 00:11:19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.00,0,0.00
14,1606,2018-01-26 00:13:32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,5.333333,0.00,0,0.00
15,1607,2018-01-26 00:13:41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.833333,0.00,0,0.00
16,1608,2018-01-26 00:15:14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,4.500000,0.00,0,0.00
17,1609,2018-01-26 00:17:14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,5.500000,0.00,0,0.00
18,1610,2018-01-26 00:17:36,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,4.666667,0.00,0,0.00
19,1611,2018-01-26 00:17:56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.00,0,0.00
20,1612,2018-01-26 00:18:14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.500000,0.00,0,0.00
21,1613,2018-01-26 00:19:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.666667,0.00,0,0.00
22,1614,2018-01-26 00:20:22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.00,0,0.00
23,1615,2018-01-26 00:20:47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,10.333333,0.00,0,0.00
24,1616,2018-01-26 00:22:52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.000000,0.00,0,0.00
25,1617,2018-01-26 00:23:42,30000.0,97200.0,20000.0,0.0,0.0,0.0,160500.0,80392.0,...,0,0,0,0,0,0,44.666667,0.99,1,0.99
26,1618,2018-01-26 00:23:52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.833333,0.00,0,0.00
27,1619,2018-01-26 00:23:58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.666667,0.00,0,0.00
28,1620,2018-01-26 00:24:03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.500000,0.00,0,0.00
29,1621,2018-01-26 00:24:24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,24.166667,0.00,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2287977,3190501,2018-02-03 14:33:31,360670.0,198729.0,0.0,0.0,0.0,0.0,237400.0,115773.0,...,2,0,1,3,3,3,6.166667,0.00,0,0.00
2287978,3190502,2018-02-03 14:33:41,49862.0,18240.0,0.0,0.0,0.0,0.0,50023.0,12480.0,...,0,0,0,1,1,1,1.833333,0.00,0,0.00
2287979,3190503,2018-02-03 14:34:42,40101.0,9930.0,0.0,0.0,0.0,0.0,42305.0,7145.0,...,0,0,0,1,1,1,1.166667,0.00,0,0.00
2287980,3190504,2018-02-03 14:34:57,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.500000,0.00,0,0.00
2287981,3190505,2018-02-03 14:35:03,10000.0,1600.0,0.0,0.0,0.0,0.0,10000.0,900.0,...,0,0,0,0,0,0,0.333333,0.00,0,0.00
2287982,3190506,2018-02-03 14:35:16,25625.0,4700.0,0.0,0.0,0.0,0.0,36475.0,2500.0,...,0,0,0,1,1,1,1.166667,0.00,0,0.00
2287983,3190507,2018-02-03 14:36:30,417193.0,148714.0,200000.0,0.0,203000.0,0.0,820102.0,101416.0,...,0,0,0,2,2,2,3.333333,0.00,0,0.00
2287984,3190508,2018-02-03 14:37:21,3306382.0,2491920.0,1000000.0,0.0,509000.0,0.0,6434135.0,3854651.0,...,5,2,4,10,10,7,20.333333,1.98,2,1.98
2287985,3190509,2018-02-03 14:37:32,412105.0,334639.0,0.0,0.0,0.0,0.0,362829.0,283117.0,...,6,0,0,2,2,2,10.333333,0.00,0,0.00
2287986,3190510,2018-02-03 14:38:07,497560.0,407662.0,0.0,0.0,0.0,0.0,211448.0,186140.0,...,0,0,0,0,0,0,6.500000,0.00,0,0.00
2287987,3190511,2018-02-03 14:39:11,110194.0,40982.0,0.0,0.0,0.0,0.0,146245.0,36041.0,...,6,3,2,1,1,1,4.166667,0.00,0,0.00
2287988,3190512,2018-02-03 14:39:20,10000.0,0.0,0.0,0.0,0.0,0.0,10000.0,0.0,...,0,0,0,0,0,0,0.000000,0.00,0,0.00
2287989,3190513,2018-02-03 14:39:27,422616.0,344190.0,0.0,0.0,0.0,0.0,879462.0,492668.0,...,0,0,0,0,0,0,9.666667,0.00,0,0.00
2287990,3190514,2018-02-03 14:41:28,328459.0,209868.0,0.0,0.0,3000.0,0.0,296805.0,147824.0,...,7,2,2,4,4,2,7.500000,0.00,0,0.00
2287991,3190515,2018-02-03 14:43:29,513885.0,382549.0,0.0,0.0,6000.0,0.0,427446.0,304766.0,...,0,0,0,7,7,6,9.833333,0.00,0,0.00
2287992,3190516,2018-02-03 14:43:47,14600.0,2100.0,0.0,0.0,0.0,0.0,12000.0,1100.0,...,0,0,0,1,1,1,0.500000,0.00,0,0.00
2287993,3190517,2018-02-03 14:44:22,190314.0,114273.0,0.0,0.0,0.0,0.0,140362.0,78286.0,...,3,3,0,2,2,2,6.333333,0.00,0,0.00
2287994,3190518,2018-02-03 14:46:19,2142278.0,2145685.0,31776.0,0.0,6000.0,0.0,2335725.0,2065428.0,...,26,20,15,23,23,15,94.833333,0.00,0,0.00
2287995,3190519,2018-02-03 14:47:38,302161.0,93379.0,200000.0,0.0,200000.0,0.0,662251.0,42021.0,...,0,0,0,0,0,0,1.333333,0.00,0,0.00
2287996,3190520,2018-02-03 14:48:34,167783.0,79367.0,0.0,0.0,0.0,0.0,352834.0,50751.0,...,3,1,0,1,1,1,6.666667,0.00,0,0.00
2287997,3190521,2018-02-03 14:48:45,462603.0,313148.0,0.0,0.0,0.0,0.0,391466.0,211257.0,...,0,0,0,0,0,0,7.000000,0.00,0,0.00
2287998,3190522,2018-02-03 14:48:50,127342.0,88717.0,0.0,0.0,0.0,0.0,130954.0,50290.0,...,0,0,0,2,2,2,3.833333,0.00,0,0.00
2287999,3190523,2018-02-03 14:48:54,261018.0,192018.0,0.0,0.0,0.0,0.0,216264.0,147264.0,...,5,4,1,4,4,4,9.833333,0.00,0,0.00
2288000,3190524,2018-02-03 14:53:49,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.500000,0.00,0,0.00
2288001,3190525,2018-02-03 14:53:54,70794.0,34239.0,0.0,0.0,0.0,0.0,78125.0,19548.0,...,0,0,0,1,1,1,1.833333,0.00,0,0.00
2288002,3190526,2018-02-03 14:54:10,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.500000,0.00,0,0.00
2288003,3190527,2018-02-03 14:55:21,10000.0,0.0,0.0,0.0,0.0,0.0,10000.0,0.0,...,0,0,0,0,0,0,0.833333,0.00,0,0.00
2288004,3190528,2018-02-03 14:56:35,131589.0,71287.0,0.0,0.0,6000.0,0.0,249356.0,39524.0,...,0,0,0,2,2,2,4.333333,0.00,0,0.00
2288005,3190529,2018-02-03 14:57:51,221984.0,122401.0,0.0,0.0,0.0,0.0,208184.0,74738.0,...,0,0,0,1,1,1,2.833333,0.00,0,0.00
2288006,3190530,2018-02-03 14:58:45,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.666667,0.00,0,0.00

In [9]:
data['avg_online_minutes'].describe()#在线时长

count    2.288007e+06
mean     1.020749e+01
std      3.895946e+01
min      0.000000e+00
25%      5.000000e-01
50%      1.833333e+00
75%      4.833333e+00
max      2.049667e+03
Name: avg_online_minutes, dtype: float64

In [20]:
data['wood_add_value'].describe()#木头添加量

count    2.288007e+06
mean     4.543069e+05
std      4.958667e+06
min      0.000000e+00
25%      0.000000e+00
50%      4.203800e+04
75%      1.531180e+05
max      1.239962e+09
Name: wood_add_value, dtype: float64

In [21]:
data['wood_reduce_value'].describe()#木头减少量

count    2.288007e+06
mean     3.698433e+05
std      3.737720e+06
min      0.000000e+00
25%      0.000000e+00
50%      9.830000e+03
75%      9.855700e+04
max      7.995875e+08
Name: wood_reduce_value, dtype: float64

In [23]:
data['stone_add_value'].describe()#石头添加量

count    2.288007e+06
mean     1.897788e+05
std      4.670620e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.214869e+09
Name: stone_add_value, dtype: float64

In [24]:
data['stone_reduce_value'].describe()#石头减少量

count    2.288007e+06
mean     1.376074e+05
std      3.370166e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      7.962378e+08
Name: stone_reduce_value, dtype: float64

In [25]:
data['ivory_add_value'].describe()#石头添加量

count    2.288007e+06
mean     8.075623e+04
std      2.220540e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.744961e+08
Name: ivory_add_value, dtype: float64

In [53]:
colummns = [column for column in data] 
len(colummns)
colummns[0]

'user_id'

In [ ]:
descs = []
for i in range(0,168):
    desc = data[colummns[i]].describe()
    print(desc)
    descs.extend(desc)

count    2.288007e+06
mean     1.529543e+06
std      9.399393e+05
min      1.000000e+00
25%      7.499925e+05
50%      1.419095e+06
75%      2.299006e+06
max      3.190530e+06
Name: user_id, dtype: float64
count                 2288007
unique                1623620
top       2018-02-24 14:47:42
freq                       28
Name: register_time, dtype: object
count    2.288007e+06
mean     4.543069e+05
std      4.958667e+06
min      0.000000e+00
25%      0.000000e+00
50%      4.203800e+04
75%      1.531180e+05
max      1.239962e+09
Name: wood_add_value, dtype: float64
count    2.288007e+06
mean     3.698433e+05
std      3.737720e+06
min      0.000000e+00
25%      0.000000e+00
50%      9.830000e+03
75%      9.855700e+04
max      7.995875e+08
Name: wood_reduce_value, dtype: float64
count    2.288007e+06
mean     1.897788e+05
std      4.670620e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.214869e+09
Name: stone_add_value, dtype: float64
count    2.288007e+06
mean     1.376074e+05
std      3.370166e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      7.962378e+08
Name: stone_reduce_value, dtype: float64
count    2.288007e+06
mean     8.075623e+04
std      2.220540e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.744961e+08
Name: ivory_add_value, dtype: float64
count    2.288007e+06
mean     3.613170e+04
std      1.782499e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.481972e+08
Name: ivory_reduce_value, dtype: float64
count    2.288007e+06
mean     5.855155e+05
std      5.868629e+06
min      0.000000e+00
25%      0.000000e+00
50%      3.458700e+04
75%      1.360010e+05
max      1.470644e+09
Name: meat_add_value, dtype: float64
count    2.288007e+06
mean     3.548102e+05
std      3.400632e+06
min      0.000000e+00
25%      0.000000e+00
50%      6.470000e+03
75%      6.605400e+04
max      8.889537e+08
Name: meat_reduce_value, dtype: float64
count    2.288007e+06
mean     7.538954e+04
std      9.662892e+05
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.637228e+08
Name: magic_add_value, dtype: float64
count    2.288007e+06
mean     4.725399e+04
std      8.811223e+05
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.637229e+08
Name: magic_reduce_value, dtype: float64
count    2.288007e+06
mean     1.436104e+02
std      1.781468e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      8.749180e+05
Name: infantry_add_value, dtype: float64
count    2.288007e+06
mean     2.267821e+02
std      1.738488e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      8.788830e+05
Name: infantry_reduce_value, dtype: float64
count    2.288007e+06
mean     1.282639e+02
std      1.334977e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.538520e+05
Name: cavalry_add_value, dtype: float64
count    2.288007e+06
mean     1.780055e+02
std      1.347096e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.703750e+05
Name: cavalry_reduce_value, dtype: float64
count    2.288007e+06
mean     1.195425e+02
std      5.958519e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      8.767537e+06
Name: shaman_add_value, dtype: float64
count    2.288007e+06
mean     1.568530e+02
std      5.958508e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      8.769162e+06
Name: shaman_reduce_value, dtype: float64